# Site settings
name: maxi.io
title: Javascript and other obscurities
email: thomas@gmail.com
username: tmaximini
description: "Hi there. My name is Thomas Maximini and I am a Javascript developer and DJ from Berlin. This is my personal homepage where you can find blog posts, projects and DJ mixes."
baseurl: ""
url: "http://maxi.io"

# Build settings
markdown: kramdown
permalinks: pretty
