# Site settings
name: Thomas Maximini
title: Javascript and Records!
email: tmaximini@gmail.com
username: tmaximini
description: "Hello. My name is Thomas and I am a web and mobile developer from Berlin."
baseurl: "http://maxi.io"

collections:
  projects:
    output: true
    permalink: /projects/:path/

exclude: [
  .git,
  .gitignore,
  .DS_Store,
  CNAME,
  svg,
  scss,
  .sass-cache,
  package.json,
  Gruntfile.js,
  node_modules,
  readme.md
]

# Build settings
markdown: kramdown
permalinks: pretty
highlighter: pygments
excerpt_separator: N/A-------N/A
