# Site settings
name: Thomas Maximini
title: Javascript and Records!
email: tmaximini@gmail.com
username: tmaximini
description: "Hi there. My name is Thomas and I am a Javascript developer and DJ from Berlin. This is my personal homepage where I occasionally blog, showcase projects and upload DJ mixes."
baseurl: ""

collections:
  projects:
    output: true
    permalink: /projects/:path/

exclude: [
  .git,
  .gitignore,
  .DS_Store,
  CNAME,
  svg,
  scss,
  .sass-cache,
  package.json,
  Gruntfile.js,
  node_modules,
  readme.md
]

# Build settings
markdown: kramdown
permalinks: pretty
