# Site settings
name: Thomas Maximini
title: Thomas Maximini - Web and Mobile Developer
email: tmaximini@gmail.com
username: tmaximini
description: "Hello. My name is Thomas and I am a web and mobile developer from Berlin."
baseurl: ""

collections:
  projects:
    output: true
    permalink: /projects/:path/

exclude: [
  .git,
  .gitignore,
  .DS_Store,
  CNAME,
  svg,
  scss,
  .sass-cache,
  package.json,
  Gruntfile.js,
  LICENSE.md,
  node_modules,
  bower_components,
  readme.md
]

# Build settings
markdown: kramdown
permalinks: pretty
highlighter: pygments
excerpt_separator: N/A-------N/A
